#!/bin/bash

get_deps() {
    file="$1"
    otool -L "$file"  | awk '{ print $1 }' | while read lib; do
        if [[ -r $lib ]]; then
            echo $lib
        fi
    done
}
app="$( basename "$0" )"
analysed="/tmp/$app.analysed.tmp"
to_be_analysed="/tmp/$app.to_be_analysed.tmp"

rm -f "$analysed" "$to_be_analysed"

recursive_deps_analyse() {
    tmpfile="/tmp/$app.tmp"
    rm -f "$tmpfile"

    cat "$to_be_analysed" | sort | uniq | while read library; do
#        echo "Analysing $library" >&2
        [[ -r "$analysed" ]] && grep -q "$library" "$analysed" && continue 
        get_deps "$library" >> "$tmpfile" 
        echo "$library" >> "$analysed"
    done

    if ! [[ -r "$tmpfile" ]]; then
        rm $to_be_analysed
        return
    fi
    cp "$tmpfile" "$to_be_analysed"
    rm -f "$tmpfile"
}

get_deps "$1" > "$to_be_analysed"

while [[ -r "$to_be_analysed" && "$( wc -l "$to_be_analysed" | awk '{ print $1}' )" -gt 0 ]]; do
    recursive_deps_analyse
done

cat "$analysed" | sort | uniq
