#!/bin/bash



get_deps() {
    file="$1"
    otool -L "$file" | grep '/opt' | awk '{ print $1 }' | while read lib; do
        if [[ -r $lib ]]; then
            echo $lib
        fi
    done
}

tmpfile="/tmp/tmp1.$$"
tmpfile2="/tmp/tmp2.$$"
results="/tmp/result.$$"

get_deps "$1" | tee $results > $tmpfile

while [[ $( wc -l <$tmpfile ) -gt 0 ]]; do
    rm -f $tmpfile2

    while read dep < $tmpfile; do
        get_deps "$dep" | tee -a $results >> $tmpfile2
    done

    cp $tmpfile2 $tmpfile
done

cat $results
rm -f $results $tmpfile $tmpfile2

    
