language: cpp
if: branch = master OR type = pull_request
os:
- linux
- osx
services:
 - docker
before_install:
- bash -x .travis-ci/before_install
script:
 - bash -x .travis-ci/ci-build
 - bash -x .travis-ci/tests
 - bash -x .travis-ci/package
deploy:
  provider: script
  script: bash -x .travis-ci/deploy
  skip_cleanup: true
  on:
    repo: GuLinux/PlanetaryImager
    branch: master

