matrix:
  include:
  - language: python
    python: 3.6
    services:
    - docker
    before_install:
    - bash -x .travis-ci/before_install
    script:
    - bash -x .travis-ci/ci-build
    - bash -x .travis-ci/tests
    - bash -x .travis-ci/package
    deploy:
      provider: releases
      api_key: "$GITHUB_OAUTH_TOKEN"
      file_glob: true
      file: packages/*
      skip_cleanup: true
      on:
        repo: GuLinux/PlanetaryImager
        all_branches: true

