matrix:
  include:
    - language: python
      python: 3.6
      services:
        - docker
      before_install:
        - bash -x .travis-ci/before_install
      script:
        - bash -x .travis-ci/ci-build
        - bash -x .travis-ci/tests
        - bash -x .travis-ci/package
      deploy:
        provider: releases
        api_key: "$GITHUB OAUTH TOKEN"
        file_glob: true
        file: packages/*
        skip_cleanup: true
        # on:
        #   tags: true 
#    - language: cpp
#      os: osx

