language: cpp
os:
- linux
- osx
services:
 - docker
before_install:
- bash -x .travis-ci/before_install
script:
 - bash -x .travis-ci/ci-build
 - bash -x .travis-ci/tests
 - bash -x .travis-ci/package
before_deploy: sudo pip install PyGithub
deploy:
  provider: script
  script: bash -x .travis-ci/deploy
  on:
    repo: GuLinux/PlanetaryImager
    all_branches: true

