matrix:
  include:
    - language: python
      python: 3.6
      before_install:
        - pwd
        - ls
        - bash -x .travis-ci/before_install
#    - language: cpp
#      os: osx

services:
  - docker

