matrix:
  include:
    - language: python
      python: 3.6
      before_install:
        - bash -x .travis-ci/before_install
      script:
        - bash -x .travis-ci/ci-build
#    - language: cpp
#      os: osx

services:
  - docker

