language: cpp
if: branch = master OR type = pull_request
matrix:
  include:
    - os: osx
    - os: linux
      env: DOCKER_IMAGE=ubuntu-19.04-x86_64
      services:
        - docker
    - os: linux
      env: DOCKER_IMAGE=ubuntu-19.04-arm32v7
      services:
        - docker
    - os: linux
      env: DOCKER_IMAGE=ubuntu-18.04-x86_64
      services:
        - docker
    - os: linux
      env: DOCKER_IMAGE=ubuntu-18.04-arm32v7
      services:
        - docker
    - os: linux
      env: DOCKER_IMAGE=ubuntu-16.04-x86_64
      services:
        - docker
    - os: linux
      env: DOCKER_IMAGE=ubuntu-16.04-arm32v7
      services:
        - docker
    - os: linux
      env: DOCKER_IMAGE=debian-testing-x86_64
      services:
        - docker
    - os: linux
      env: DOCKER_IMAGE=debian-testing-arm32v7
      services:
        - docker
    - os: linux
      env: DOCKER_IMAGE=fedora-27-x86_64
      services:
        - docker
    - os: linux
      env: DOCKER_IMAGE=windows-x86_64
      services:
        - docker
before_install:
  - bash -x .travis-ci/before_install
script: bash .travis-ci/ci-build && bash .travis-ci/tests && bash .travis-ci/package
deploy:
  provider: script
  script: bash -x .travis-ci/deploy
  skip_cleanup: true
  on:
    repo: GuLinux/PlanetaryImager
    branch: master
