language: cpp
if: branch = master OR type = pull_request
matrix:
  include:
    - os: osx
    - os: linux
      env: DOCKER_IMAGE=ubuntu-19.04-x86_64 CMAKE_BINARY=cmake DEST_OS=linux" DOCKER_IMAGE_ARCHITECTURE=amd64
      dist: xenial
      services:
        - docker
    - os: linux
      env: DOCKER_IMAGE=ubuntu-18.04-x86_64 CMAKE_BINARY=cmake DEST_OS=linux" DOCKER_IMAGE_ARCHITECTURE=amd64
      dist: xenial
      services:
        - docker
    - os: linux
      env: DOCKER_IMAGE=ubuntu-16.04-x86_64 CMAKE_BINARY=cmake DEST_OS=linux" DOCKER_IMAGE_ARCHITECTURE=amd64
      dist: xenial
      services:
        - docker
    - os: linux
      env: DOCKER_IMAGE=debian-stretch-x86_64 CMAKE_BINARY=cmake DEST_OS=linux" DOCKER_IMAGE_ARCHITECTURE=amd64
      dist: xenial
      services:
        - docker
    - os: linux
      env: DOCKER_IMAGE=debian-buster-x86_64 CMAKE_BINARY=cmake DEST_OS=linux" DOCKER_IMAGE_ARCHITECTURE=amd64
      dist: xenial
      services:
        - docker
    - os: linux
      env: DOCKER_IMAGE=fedora-29-x86_64 CMAKE_BINARY=cmake DEST_OS=linux" DOCKER_IMAGE_ARCHITECTURE=amd64
      dist: xenial
      services:
        - docker
    - os: linux
      env: DOCKER_IMAGE=fedora-30-x86_64 CMAKE_BINARY=cmake DEST_OS=linux" DOCKER_IMAGE_ARCHITECTURE=amd64
      dist: xenial
      services:
        - docker
    - os: linux
      env: DOCKER_IMAGE=fedora-31-x86_64 CMAKE_BINARY=cmake DEST_OS=linux" DOCKER_IMAGE_ARCHITECTURE=amd64
      dist: xenial
      services:
        - docker
    - os: linux
      env: DOCKER_IMAGE=windows-x86_64 CMAKE_BINARY=x86_64-w64-mingw32.static-cmake DEST_OS=windows" DOCKER_IMAGE_ARCHITECTURE=amd64
      dist: xenial
      services:
        - docker
before_install:
  - bash -x .travis-ci/before_install
script: bash -x .travis-ci/ci-build && bash -x .travis-ci/tests && bash -x .travis-ci/package
deploy:
  provider: script
  script: bash -x .travis-ci/deploy
  skip_cleanup: true
  on:
    repo: GuLinux/PlanetaryImager
    branch: master
