cp "$( dirname "$BASH_SOURCE")/configuration-${DEB_CONFIG_NAME}.cmake" "$PWD"
cat <<EOF
FROM ${DEB_BASE_IMAGE}
RUN apt-get update && apt-get install -y \
    autoconf \
    qtbase5-dev \
    build-essential \
    cmake \
    libopencv-dev \
    libboost-all-dev \
    git \
    libudev-dev \
    libccfits-dev \
    && apt-get clean
EOF

. ../commons/Dockerfile.libusb.in
. ../commons/Dockerfile.workdir.in

cat <<EOF
COPY configuration-${DEB_CONFIG_NAME}.cmake /
ENV CMAKE_EXTRA_OPTIONS -DCMAKE_INCLUDE_EXT_FILE=/configuration-${DEB_CONFIG_NAME}.cmake -DCPACK_GENERATOR=DEB ${CMAKE_EXTRA_OPTIONS}
EOF
