#!/bin/bash
set -e
if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
    sudo apt-get install -y binfmt-support
    docker run --rm --privileged multiarch/qemu-user-static:register
    source ~/virtualenv/python3.6/bin/activate
fi
if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
    bash support/osx/install-deps
fi
