#!/bin/bash

#if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
source ~/virtualenv/python3.6/bin/activate
#fi

source "${TRAVIS_BUILD_DIR}/build/scripts/version.sh"
cat <<EOF
Deployment variables:
 - GITHUB_OAUTH_USER=${GITHUB_OAUTH_USER}
 - GITHUB_OAUTH_TOKEN=<secret>
 - TRAVIS_BUILD_DIR=${TRAVIS_BUILD_DIR}
 - TRAVIS_COMMIT=${TRAVIS_COMMIT}
 - TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
 - PLANETARY_IMAGER_VERSION=${PLANETARY_IMAGER_VERSION}
 - TRAVIS_COMMIT_MESSAGE=${TRAVIS_COMMIT_MESSAGE}
EOF

pip3 install PyGithub
python3 "scripts/release-travis.py" packages/*
