#!/bin/bash
RELEASE="${1:-yakkety}"
base_image_name="gulinux/planetaryimager_build:ubuntu_${RELEASE}_arm_base"

if [[ -z "$( docker images -q $base_image_name )" ]] && ! docker pull $base_image_name 2>/dev/null ; then
    docker run -it --rm -v $PWD:/target --privileged ubuntu:16.10 /target/prepare-fs "${RELEASE}"
    (
      cd base-image
      set -x
      docker build -t $base_image_name .
    )
fi
rm -rf "base-image/arm-root.tar"

