#!/bin/bash
root="/arm-root"
RELEASE="$1"

apt-get update && apt-get install -y qemu-user-static binfmt-support debootstrap

update-binfmts --enable
alias qemu-debootstrap=debootstrap
debootstrap --foreign --arch armhf $RELEASE "$root" http://ports.ubuntu.com/

cp -av "$( which qemu-arm-static )" $root/usr/bin
DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true \
    LC_ALL=C LANGUAGE=C LANG=C chroot $root/ /debootstrap/debootstrap --second-stage
DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true \
    LC_ALL=C LANGUAGE=C LANG=C chroot $root dpkg --configure -a
rm -rf $root/debootstrap

cat >"$root"/etc/apt/sources.list <<EOF
deb http://ports.ubuntu.com/ubuntu-ports ${RELEASE} main restricted universe multiverse
EOF

mkdir -p /target/base-image
(
  TARGET_FILE=/target/base-image/arm-root.tar
  set -x
  rm -rf "$TARGET_FILE"
  tar --numeric-owner --create --auto-compress --file "$TARGET_FILE" --directory "$root" --transform='s,^./,,' .
)
rm -rf "$root"

