#!/bin/bash

for d in *; do
  [[ -d "$d" ]] && [[ -r "$d/Dockerfile" ]] || continue
  (
    echo "===================================== Preparing image for $d"
    set -e
    cd "$d"
    . image-env
    if [[ -x prepare-image ]]; then
      ./prepare-image
    fi
    docker build -t gulinux/planetaryimager_build:${image_name}-${image_version} "$@" .
    echo "===================================== Finished building $d"
  ) || exit 1
done 
