#!/bin/bash

[[ -r "$HOME/.config/planetaryimager_packaging_images_env.conf" ]] && . "$HOME/.config/planetaryimager_packaging_images_env.conf"

dirs=""
while [[ -n "$1" ]] && [[ "$1" != "--" ]]; do
  case "$1" in
    -d|--dir)
      dirs="$dirs $2"; shift
      ;;
  esac
  shift
done
shift

[[ -z "$dirs" ]] && dirs=*
tmpfile=/tmp/$( basename $0).tmp.$$
rm -f $tmpfile
for d in $dirs; do
  [[ -d "$d" ]] && ( [[ -r "$d/Dockerfile" ]] || [[ -x "$d/prepare-image" ]] ) || continue
  (
    echo "===================================== Preparing image for $d"
    set -e
    cd "$d"
    . image-env
    if [[ -x prepare-image ]]; then
      ./prepare-image
    fi
    docker build -t gulinux/planetaryimager_build:${image_name}-${image_version} "$@" .
    [[ $? == 0 ]] && status=ok || status=error
    echo "===================================== Finished building $d: $status"
    echo "Image $d result: [$status]" >> $tmpfile
  ) 
done 
column -t < $tmpfile
rm -f $tmpfile
