#!/bin/bash

dirs=""
while [[ -n "$1" ]] && [[ "$1" != "--" ]]; do
  case "$1" in
    -d|--dir)
      dirs="$dirs $2"; shift
      ;;
  esac
  shift
done
shift

[[ -z "$dirs" ]] && dirs=*

for d in $dirs; do
  [[ -d "$d" ]] && ( [[ -r "$d/Dockerfile" ]] || [[ -x "$d/prepare-image" ]] ) || continue
  (
    echo "===================================== Preparing image for $d"
    set -e
    cd "$d"
    . image-env
    if [[ -x prepare-image ]]; then
      ./prepare-image
    fi
    docker build -t gulinux/planetaryimager_build:${image_name}-${image_version} "$@" .
    echo "===================================== Finished building $d"
  ) || exit 1
done 
