UBUNTU_BASE_IMAGE="ubuntu:16.04"
. ../ubuntu-commons/Dockerfile.in

cat <<EOF
FROM ${UBUNTU_BASE_IMAGE}
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    wget \
    autopoint autoconf automake bash bison bzip2 flex \
    libgdk-pixbuf2.0-dev gettext git gperf intltool make \
    sed libffi-dev libtool p7zip-full patch \
    perl python ruby scons unzip wget xz-utils libtool-bin \
    && apt-get clean
RUN cd / && git clone https://github.com/mxe/mxe.git && cd /mxe && \
    make MXE_TARGETS='x86_64-w64-mingw32.static i686-w64-mingw32.static' MXE_PLUGIN_DIRS='/mxe/plugins/gcc5' \
        ccfits boost cmake opencv qtbase

ENV PATH=/mxe/usr/bin:$PATH


EOF
. ../commons/Dockerfile.workdir.in
