#!/bin/bash

CMAKE_BIN="${CMAKE_BIN:-cmake}"
PACKAGE_COMMAND="${PACKAGE_COMMAND:-make package}"

set -e
${CMAKE_BIN} \
          -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH} \
          "$@" \
          /code && \
          make ${MAKE_OPTS} && $PACKAGE_COMMAND

if [ -r package_name.cfg ]; then
    . package_name.cfg
    if [ -n "${PACKAGE_INSTALL_COMMAND}" ]; then
        "${PACKAGE_INSTALL_COMMAND}" "${CPACK_PACKAGE_FILENAME}"
    fi
    cp -av "${CPACK_PACKAGE_FILENAME}" "/dest/${CPACK_PACKAGE_FILENAME}"
fi

