cp "$( dirname "$BASH_SOURCE")/configuration-${FEDORA_VERSION}.cmake" "$PWD"

cat <<EOF
FROM ${FEDORA_BASE_IMAGE}
RUN yum install -y \
    rpm-build \
    autoconf \
    automake \
    qt5-qtbase-devel \
    gcc-c++ \
    cmake \
    opencv-devel \
    boost-devel \
    git \
    libusb-devel \
    CCfits-devel \
    && yum clean all -y
EOF
# . ../commons/Dockerfile.libusb.in
. ../commons/Dockerfile.workdir.in

cat <<EOF
COPY configuration-${FEDORA_VERSION}.cmake /
ENV CMAKE_EXTRA_OPTIONS -DCMAKE_INCLUDE_EXT_FILE=/configuration-${FEDORA_VERSION}.cmake
EOF

