FROM ubuntu:16.04
RUN apt-get update && apt-get install -y qtbase5-dev build-essential cmake libusb-1.0-0-dev cimg-dev libopencv-dev libqcustomplot-dev libboost-all-dev && apt-get clean
WORKDIR /build

