#!/bin/bash
img_url="http://cdimage.ubuntu.com/ubuntu/releases/16.04/release/ubuntu-16.04-preinstalled-server-armhf+raspi2.img.xz"
clear="false"
is_true() {
  [[ "$1" == "true" ]]
}

while [[ -n "$1" ]]; do
  case "$1" in
    -c|--clear)
      clear=true
      ;;
    -u|--url)
    img_url="$2"; shift
      ;;
  esac
  shift
done

img_file="$( basename "$img_url")"
img="${img_file%.*}"
[[ -r "$img_file" ]] || curl -O -L "$img_url"
[[ -r "$img" ]] || unxz -k "$img_file"
is_true "$clear" && rm -f "$img_file"
[[ -r "1.img" ]] || 7z x "$img" 1.img
is_true "$clear" && rm -f "$img"
7z x -oroot 1.img 
is_true "$clear" && rm -f "$img" 
