#!/bin/bash
CCFITS_VERSION="2.5"
set -e

if ! which brew &>/dev/null; then
    echo "You must install brew in order to run this script" >&2
    exit 1
fi

script_dir="$( cd "$( dirname "$0")"; pwd )"

if [ "$1" != "skip-brew" ]; then
    while read pkg; do 
        if ! brew list "$pkg" &>/dev/null; then
            brew install "$pkg"
        fi
    done < "$script_dir/homebrew_deps"
fi

if ! [ -r "$(brew --prefix)/lib/libCCfits.a" ]; then
(
    wget "https://heasarc.gsfc.nasa.gov/fitsio/CCfits/CCfits-${CCFITS_VERSION}.tar.gz"
    tar xf "CCfits-${CCFITS_VERSION}.tar.gz"
    rm -f "CCfits-${CCFITS_VERSION}.tar.gz"
    cd CCfits
    ./configure --prefix="$(brew --prefix)" --enable-static --disable-shared
    make -j4
    make install
    cd ..
    rm -rf CCfits
)
fi

