
cat >&2 <<EOF
You need to copy the MacOSX10.11.sdk.tar.xz into this folder to get the cross compiler working.
Instructions:
Download xcode fron https://developer.apple.com/download/more/, choosing version 7.3
    git clone https://github.com/tpoechtrager/osxcross
    ./tools/gen_sdk_package_darling_dmg.sh Xcode_7.3.dmg
EOF


cat <<EOF
FROM ubuntu:16.10
RUN apt-get update && apt-get install -y git build-essential cmake clang wget autoconf automake libtool-bin libtool pkg-config && \
    git clone https://github.com/tpoechtrager/osxcross
COPY MacOSX10.11.sdk.tar.xz /osxcross/tarballs/
RUN cd /osxcross && UNATTENDED=1 ./build.sh
ENV PATH=/osxcross/target/bin:\${PATH} CC=o64-clang CXX=o64-clang++ MACOSX_DEPLOYMENT_TARGET=10.7 UNATTENDED=1
RUN osxcross-macports install openssl && osxcross-macports remove-dylibs
EOF

LIBUSB_CONFIGURE_OPTS="--host=x86_64-apple-darwin15"
. ../commons/Dockerfile.libusb.in

QT_MAJOR_MINOR="5.8"
QT_VERSION="${QT_MAJOR_MINOR}.0"
cat <<EOF
COPY macx-clang-qmake.conf /
RUN cd / && wget http://download.qt.io/official_releases/qt/${QT_MAJOR_MINOR}/${QT_VERSION}/single/qt-everywhere-opensource-src-${QT_VERSION}.tar.gz && \
    tar xf qt-everywhere-opensource-src-${QT_VERSION}.tar.gz && \
    rm -f qt-everywhere-opensource-src-${QT_VERSION}.tar.gz && \
    mv /macx-clang-qmake.conf /qt-everywhere-opensource-src-5.8.0/qtbase/mkspecs/macx-clang/qmake.conf && \ 
    ./configure -opensource -c++std c++11 -confirm-license -xplatform macx-clang -recheck-all -device-option CROSS_COMPILE=apple-darwin15 -nomake examples -nomake tests -no-cups -no-glib  -no-sql-db2 -no-sql-ibase -no-sql-oci -no-sql-tds -no-sql-mysql -no-sql-psql -no-sql-odbc -no-sql-sqlite2 -prefix /opt/qt5 -qt-libpng   -qt-libjpeg   -qt-zlib   -qt-pcre  --ssl -openssl-linked -release -no-pch -qt-zlib -qt-pcre -optimized-qmake -no-reduce-relocations 
EOF
