#!/bin/bash
mkdir PlanetaryImager.app
make install DESTDIR="$PWD/PlanetaryImager.app"

fix_libraries() {
    binary="$1"
    python /fix_libraries.py \
                            --libs-dest PlanetaryImager.app/Contents/lib \
                            --otool x86_64-apple-darwin15-otool \
                            --install-name-tool x86_64-apple-darwin15-install_name_tool \
                            "$binary"

}

fix_libraries PlanetaryImager.app/Contents/bin/planetary_imager

cp -av /opt/local/libexec/qt5/plugins/platforms PlanetaryImager.app/Contents/bin
cp -av /opt/local/libexec/qt5/plugins/imageformats PlanetaryImager.app/Contents/bin

find PlanetaryImager.app/Contents/lib -type f -name *.dylib | while read file; do
    fix_libraries "$file"
done

find PlanetaryImager.app/Contents/lib/PlanetaryImager/drivers -type f -name *.so | while read file; do
    fix_libraries "$file"
done


find PlanetaryImager.app/Contents/bin -type f -name *.dylib | while read file; do
    fix_libraries "$file"
done


find PlanetaryImager.app/Contents/bin -type f -name planetary_imager_* | while read file; do
    fix_libraries "$file"
done

. package_name.cfg
CPACK_BASE_PACKAGE_FILENAME="$( basename "$CPACK_PACKAGE_FILENAME" .tar.gz | sed 's/Darwin/MacOSX/g')"

PACKAGING_METHOD="${PACKAGING_METHOD:-dmg}"
if [[ "$PACKAGING_METHOD" == tar ]]; then
  # Package as an old .tar.gz archive... less nice
  CPACK_PACKAGE_FILENAME="$CPACK_BASE_PACKAGE_FILENAME.tar.gz"
  tar cvf - PlanetaryImager.app | gzip -9 - > "$CPACK_PACKAGE_FILENAME"
else
  # Create a native "dmg" image.. nice, but bigger file size
  CPACK_PACKAGE_FILENAME="$CPACK_BASE_PACKAGE_FILENAME.dmg"
  mkdir dmg
  mv PlanetaryImager.app dmg/Planetary\ Imager.app
  ln -s /Applications dmg/
  cp /DS_Store dmg/.DS_Store
  set -x
  genisoimage -V "PlanetaryImager" -D  -no-pad -apple -R -o "PlanetaryImager-uncompressed.dmg" dmg && rm -rf dmg
  dmg dmg PlanetaryImager-uncompressed.dmg "$CPACK_PACKAGE_FILENAME" >/dev/null 2>&1
  set +x
fi

echo "CPACK_PACKAGE_FILENAME=$CPACK_PACKAGE_FILENAME" > package_name.cfg
