#!/bin/bash

root="$( dirname "$( readlink -f "$0" )" )/raspberry-root"
project="$( readlink -f "$( dirname "$0" )/../../..")"
rrun() {


#  mount --rbind /dev "$root/dev"
#  mount --rbind /sys "$root/sys"
#  mount --rbind /proc "$root/proc"
#  mount --rbind "$project" "$root/PlanetaryImager"
  chroot "$root" "$@"
#  umount "$root/PlanetaryImager"
#  umount "$root/proc"
#  umount "$root/sys"
#  umount "$root/dev"
}
