#!/bin/bash
version="$1"
outdir="${2:-$PWD}"

cleanup_unused_files() {
    rm -rf .git
    find src/drivers/qhy/QHYCCD_Linux/ -name "*.bin" -or -name "*.dylib" -or -name "*osx*" -or -name "sample" -or -name "doc"| while read f; do 
      rm -vrf "$f"
    done
    find src/drivers/zwo_asi/ -name "doc" -or -name "armv5" -or -name "armv8" -or -name "mac" -or -name "demo"| while read f; do
      rm -vrf "$f"
    done
    rm -rf test
}

if [[ -z "$version" ]] || ! [[ -d "$outdir" ]]; then
	echo "Usage: $0 version [output-directory]" >&2
	exit 1
fi
outdir="$( readlink -f "$outdir")"
tmpdir="/tmp/planetary-imager-release-creator-$RANDOM"
mkdir -p "$tmpdir"
cd "$tmpdir"
git clone "https://github.com/GuLinux/PlanetaryImager.git" PlanetaryImager-$version
cd PlanetaryImager-$version
git checkout v$version
git submodule init && git submodule update --recursive

cleanup_unused_files
cd ..
7z a "$outdir/PlanetaryImager-$version.7z" "PlanetaryImager-$version"
7z a "$outdir/PlanetaryImager-$version.zip" "PlanetaryImager-$version"
tar cf "$outdir/PlanetaryImager-$version.tar" "PlanetaryImager-$version"
gzip -k -9 "$outdir/PlanetaryImager-$version.tar"
bzip2 -k -9 "$outdir/PlanetaryImager-$version.tar"
cd $outdir
rm -rf "$tmpdir" "$outdir/PlanetaryImager-$version.tar"

