#!/bin/bash
version="$1"
outdir="${2:-$PWD}"
if [[ -z "$version" ]] || ! [[ -d "$outdir" ]]; then
	echo "Usage: $0 version [output-directory]" >&2
	exit 1
fi
outdir="$( readlink -f "$outdir")"
tmpdir="/tmp/planetary-imager-release-creator-$RANDOM"
mkdir -p "$tmpdir"
cd "$tmpdir"
git clone "https://github.com/GuLinux/PlanetaryImager.git" PlanetaryImager-$version
cd PlanetaryImager-$version
git checkout v$version
git submodule init && git submodule update --recursive
rm -rf .git 
cd ..
tar cf "$outdir/PlanetaryImager-$version.tar" PlanetaryImager-$version
bzip2 -9 "$outdir/PlanetaryImager-$version.tar"
cd $outdir
rm -rf "$tmpdir"

