#!/bin/bash
project_dir="$( cd "$( dirname "$0")/.."; pwd )"
travis_yml="$project_dir/.travis.yml"

cat > "$travis_yml" <<EOF
language: cpp
if: branch = master OR type = pull_request
matrix:
  include:
    - os: osx
EOF

"$project_dir/support/docker/docker.py" list | while read docker_image; do
    docker_tag="$( cut -d: -f2 <<<"$docker_image")"
    if [ "${docker_tag:0:7}" == "windows" ]; then
        CMAKE_BINARY="${docker_tag:8}-w64-mingw32.static-cmake"
        DEST_OS="windows"
    fi
    DOCKER_IMAGE_ARCHITECTURE="$( docker inspect "$docker_image" | python -c "import sys; import json; print(json.load(sys.stdin)[0]['Architecture'])" )"
    cat >> "$travis_yml" <<EOF
    - os: linux
      env: DOCKER_IMAGE=${docker_tag} CMAKE_BINARY=${CMAKE_BINARY:-cmake} DEST_OS=${DEST_OS:-linux}" DOCKER_IMAGE_ARCHITECTURE=${DOCKER_IMAGE_ARCHITECTURE}
      services:
        - docker
EOF
done

cat >> "$travis_yml" <<EOF
before_install:
  - bash -x .travis-ci/before_install
script: bash .travis-ci/ci-build && bash .travis-ci/tests && bash .travis-ci/package
deploy:
  provider: script
  script: bash -x .travis-ci/deploy
  skip_cleanup: true
  on:
    repo: GuLinux/PlanetaryImager
    branch: master
EOF
