UBUNTU_BASE_IMAGE="ubuntu:16.04"
MXE_PARALLEL_JOBS=${MXE_PARALLEL_JOBS:-3}
MXE_PARALLEL_CPU_JOBS=${MXE_PARALLEL_CPU_JOBS:-6}
cat >&2 <<EOF
MXE Settings:

MXE_PARALLEL_JOBS=$MXE_PARALLEL_JOBS
MXE_PARALLEL_CPU_JOBS=$MXE_PARALLEL_CPU_JOBS
Press any key or wait 10 seconds to continue, or CTRL+C to stop
EOF
read -t 10 -s -n 1

[[ "$MXE_ARCH" == x32 ]] && MXE_PREFIX=i686-w64-mingw32.shared || MXE_PREFIX=x86_64-w64-mingw32.shared
cat <<EOF
FROM ${UBUNTU_BASE_IMAGE}
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    wget \
    autopoint autoconf automake bash bison bzip2 flex \
    libgdk-pixbuf2.0-dev gettext git gperf intltool make \
    sed libffi-dev libtool p7zip-full patch \
    perl python ruby scons unzip wget xz-utils libtool-bin \
    && apt-get clean
RUN cd / && git clone https://github.com/mxe/mxe.git && cd /mxe && \
    make -j $MXE_PARALLEL_JOBS JOBS=$MXE_PARALLEL_CPU_JOBS MXE_TARGETS='$MXE_PREFIX' MXE_PLUGIN_DIRS='/mxe/plugins/gcc5' \
        nsis ccfits boost cmake qtbase qtdeclarative \
        ffmpeg jpeg libpng tiff opencv \ 
    	clean-junk 

ENV PATH=/mxe/usr/bin:\$PATH


RUN cd /tmp && wget --quiet http://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio3410.tar.gz && \
    wget --quiet https://heasarc.gsfc.nasa.gov/fitsio/CCfits/CCfits-2.5.tar.gz && \
    tar xf cfitsio3410.tar.gz && tar xf CCfits-2.5.tar.gz && \ 
    cd /tmp/cfitsio && ./configure --host=$MXE_PREFIX --prefix=/mxe/usr/$MXE_PREFIX FC=${MXE_PREFIX}-gfortran && make -j$MXE_PARALLEL_CPU_JOBS && make install && \
    cd /tmp/CCfits && ./configure  --host=$MXE_PREFIX --prefix=/mxe/usr/$MXE_PREFIX --build=static --enable-static --disable-shared --with-cfitsio=/mxe/usr/$MXE_PREFIX && \
    make -j$MXE_PARALLEL_CPU_JOBS && make install && cd / && rm -rf /tmp/*
#RUN ln -s /mxe/usr/bin/${MXE_PREFIX}-makensis /usr/bin/makensis

ENV CMAKE_BIN=${MXE_PREFIX}-cmake

COPY deps.cmake /
ENV CMAKE_EXTRA_OPTIONS -DCMAKE_INCLUDE_POST_FILE=/deps.cmake -Dcflags_fpic=Off -DCMAKE_INSTALL_PREFIX=/ -DCPACK_GENERATOR=ZIP
EOF
#CMAKE_BIN=${MXE_PREFIX}-cmake . ../commons/Dockerfile.opencv.in  
. ../commons/Dockerfile.workdir.in
