#!/bin/bash
set -e
if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
    current_arch="$(uname -i)"
    if [ "$current_arch" != "${IMAGE_ARCH}" ]; then
        echo "Architecture $current_arch different than specified docker image ($DOCKER_IMAGE); enabling qemu-arm-static"
        sudo apt-get install -y binfmt-support
        docker run --rm --privileged multiarch/qemu-user-static:register
    fi
fi
if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
    bash support/osx/install-deps
    brew install python@3
fi
echo "export GIT_COMMIT_DATE=\"$(git show -s --format='%cd' --date=short | tr -d '-')\"" > ${TRAVIS_BUILD_DIR}/git_commit_date.sh
cat ${TRAVIS_BUILD_DIR}/git_commit_date.sh
