#!/bin/bash
CMAKE_BIN="${CMAKE_BIN:-cmake}"
set -x
${CMAKE_BIN} /code \
          -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH} \
          -DCMAKE_INSTALL_PREFIX=/usr \
          -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} \
          -DPACKAGE_VERSION_SUFFIX=${PACKAGE_VERSION_SUFFIX} \
          -DPACKAGE_NAME_SUFFIX=${PACKAGE_NAME_SUFFIX} \
          ${CMAKE_EXTRA_OPTIONS} ${CMAKE_OVERRIDE_OPTIONS} && \
          make ${MAKE_OPTS} && make package
had_errors=$?
if [[ "$had_errors" != 0 ]]; then
    exit ${had_errors}
fi

. package_name.cfg


chown 1000:1000 "/dest/${CPACK_PACKAGE_FILENAME}"
if [[ -n "${TEST_PACKAGE_CMD}" ]] && ! "${TEST_PACKAGE_CMD}" "${CPACK_PACKAGE_FILENAME}"; then
    cp "${CPACK_PACKAGE_FILENAME}" "/dest/${CPACK_PACKAGE_FILENAME}.failedcheck"
    exit 1
fi

cp "${CPACK_PACKAGE_FILENAME}" /dest/

#set +x
# if [[ $had_errors != 0 ]]; then
#     echo "Error on container execution; please touch the file /tmp/on_error_handler to continue: "
#     echo "docker exec -it $(hostname) touch /tmp/on_error_handler"
#     while ! [[ -r /tmp/on_error_handler ]]; do sleep 1; done
# fi
