#!/bin/bash
set -x
cmake /code \
          -DEXTRA_LIBRARIES=udev \
          -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH} \
          -DCMAKE_INSTALL_PREFIX=/usr \
          -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} \
          -DCPACK_GENERATOR=${CPACK_GENERATOR} \
          -DPACKAGE_VERSION_SUFFIX=${PACKAGE_VERSION_SUFFIX} \
          -DPACKAGE_NAME_SUFFIX=${PACKAGE_NAME_SUFFIX} \
          -DCPACK_PACKAGE_DIRECTORY=/dest \
          ${CMAKE_EXTRA_OPTIONS} && \
          make ${MAKE_OPTS} && make package
