version: '2'
services:
    planetaryimager-build:
        image: ${COMPOSE_IMAGE}
        volumes:
            - ../../:/code
            - ${DEST}:/dest
            - ./compose-entrypoint:/compose-entrypoint

        command: /compose-entrypoint

        environment:
            - CMAKE_BUILD_TYPE
            - PACKAGE_VERSION_SUFFIX
            - PACKAGE_NAME_SUFFIX
            - MAKE_OPTS=${MAKE_OPTS}
            - CMAKE_OVERRIDE_OPTIONS=${CMAKE_OVERRIDE_OPTIONS}
            - DEBUG_BUILD=${DEBUG_BUILD}

